services:
  db:
    image: postgres:16
    container_name: project_name
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project_name_network

volumes:
  postgres_data:

networks:
  javademo_network:
    driver: bridge
